### PR TITLE
Adding support for ohNet split headers.

### PR DESCRIPTION
**Pull request by DoomHammer**
It would be nice to add support for ohNet after split. Without this ohTopology doesn't seem to be building at all.

### CODE REVIEW

**Comment by SimonChisholm** [comment]
I don't think this is required now that ohTopology builds without dependency on ohNetGenerated.  I was happy with this patch in principle so let me know if you'd still like it to be applied.

**Comment by DoomHammer** [comment]
Yes, it is not required for ohTopology now. Still, it might be useful for anybody wanting to grab ohNetGenerated instead of generating needed proxies during build.

I understand the main advantage of build-time generation is that you only compile and link what you actually need, right?

**Comment by SimonChisholm** [comment]
Looking at the patch more closely, I don't think it can work correctly.  There are various references into an ohNet folder in the dependencies tree.  If ohNetGenerated was ever fetched as a pre-compiled dependency, it'd be placed in an ohNetGenerated folder, alongside the ohNet folder.

In answer to your question, build-time generation of proxies is very handy for us because it avoids lots of swapping between repos, (re-)publishing constantly, while developing a service.  I can see that this'll be less of an issue for developers who only work with stable services.

**Comment by DoomHammer** [comment]
Thanks, I will keep that in mind.

**Pull request closed without merging**
